(ql:quickload :muddler)

(defvar tagger (muddler:load-tagger #p"ipadic-2.7.0/"))
(print "load-tagger done!")
(terpri)
(print (muddler:parse tagger "今日の天気は晴れです"))
(terpri)
(print (muddler:parse tagger "裏庭には二羽庭には二羽にわとりがいる"))
(terpri)
(print (muddler:parse tagger "これははにわです"))
(terpri)
